/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulajframe;

import javax.swing.JOptionPane;

/**
 *
 * @author branca
 */
public class Tlproduto extends javax.swing.JFrame {
    Produto pro = new Produto();

    public Tlproduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Descrição = new javax.swing.JTextField();
        Bt_novo = new javax.swing.JButton();
        Bt_pesquisar = new javax.swing.JButton();
        Bt_cancelar = new javax.swing.JButton();
        Bt_salvar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo");

        Codigo.setEditable(false);
        Codigo.setEnabled(false);

        jLabel2.setText("Descrição");

        Descrição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriçãoActionPerformed(evt);
            }
        });

        Bt_novo.setText("Novo");
        Bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_novoActionPerformed(evt);
            }
        });

        Bt_pesquisar.setText("Pesquisar");
        Bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_pesquisarActionPerformed(evt);
            }
        });

        Bt_cancelar.setText("Cancelar");
        Bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_cancelarActionPerformed(evt);
            }
        });

        Bt_salvar.setText("Salvar");
        Bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Bt_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bt_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bt_pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bt_cancelar)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(Descrição)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descrição, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_novo)
                    .addComponent(Bt_pesquisar)
                    .addComponent(Bt_cancelar)
                    .addComponent(Bt_salvar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescriçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriçãoActionPerformed

    private void Bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_Bt_cancelarActionPerformed

    private void Bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_novoActionPerformed
        this.Codigo.setText("");
        this.Descrição.setText("");
    }//GEN-LAST:event_Bt_novoActionPerformed

    private void Bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_salvarActionPerformed
          if (this.Codigo.getText().length() > 0){
                    pro.setCodigo(Integer.parseInt(this.Codigo.getText()));
          }else{
              pro.setCodigo(1);
            }
          pro.setDescrição(this.Descrição.getText());
          JOptionPane.showMessageDialog(null, "O produto foi salvo como: " +  pro.getDescrição());
    }//GEN-LAST:event_Bt_salvarActionPerformed

    private void Bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_pesquisarActionPerformed
         this.Codigo.setText(this.pro.getCodigo() + "");
         this.Descrição.setText(this.pro.getDescrição());
    }//GEN-LAST:event_Bt_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tlproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tlproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tlproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tlproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tlproduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_cancelar;
    private javax.swing.JButton Bt_novo;
    private javax.swing.JButton Bt_pesquisar;
    private javax.swing.JButton Bt_salvar;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Descrição;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
